version: '3.7'
services:
   mysql_db_container:
     image: mysql:latest
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: database
     ports:
       - 3307:3306
     volumes:
       - mysql_db_data_container:/var/lib/mysql
   adminer_container:
     image: adminer:latest
     restart: always
     environment:
       ADMINER_DEFAULT_SERVER: mysql_db_container
     ports:
       - 8081:8080

volumes:
   mysql_db_data_container: